name: Test and Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        strategy:
            matrix:
                node-version: [22.x, 24.x]

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: deno ci

            - name: Validate
              run: npm test
